#!/bin/bash -e
ADK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../"
DOC_SRC_DIR="$ADK_ROOT/Documentation/"
DOC_OUT_DIR="$DOC_SRC_DIR/api_docs/"

# Delete artifacts generated by doxygen and sphinx
finish() {
    rm -rf "$DOC_SRC_DIR/_api_docs/"
    rm -rf "$DOC_SRC_DIR/api_docs/doctrees/"
    rm -rf "$DOC_SRC_DIR/api_docs//html/_sources/_api_docs"
}
trap finish EXIT

install_doxygen() {
    if ! doxygen --version > /dev/null 2>&1; then
        echo "doxygen not installed. Installing..."
        case "$(uname)" in
            "Darwin")
                brew install doxygen
                ;;
            "Linux")
                apt-get update
                apt-get install -y doxygen
                ;;
            *)
                echo "Unsupported system"
                exit 1
                ;;
        esac
    fi
}

install_pip() {
    if ! pip3 --version > /dev/null 2>&1; then
        echo "pip3 not installed. Installing..."
        case "$(uname)" in
            "Darwin")
                brew postinstall python3
                ;;
            "Linux")
                apt-get update
                apt-get install -y python3-pip
                ;;
            *)
                echo "Unsupported system"
                exit 1
                ;;
        esac
    fi
}

install_pip_package() {
    PACKAGE_TO_INSTALL=$1
    PACKAGE_VERSION_TO_INSTALL=$2
    if ! pip3 show "$PACKAGE_TO_INSTALL" > /dev/null 2>&1; then
        echo "$PACKAGE_TO_INSTALL not installed. Installing..."
        case "$(uname)" in
            "Darwin")
                pip3 install "$PACKAGE_TO_INSTALL"=="$PACKAGE_VERSION_TO_INSTALL"
                ;;
            "Linux")
                pip3 install "$PACKAGE_TO_INSTALL"=="$PACKAGE_VERSION_TO_INSTALL"
                ;;
            *)
                echo "Unsupported system"
                exit 1
                ;;
        esac
    fi
}

if ! python3 --version > /dev/null 2>&1; then
    echo "****************************************************************************"
    echo "To generate documenation for HomeKit ADK please install Python3 for your OS."
    echo "****************************************************************************"
    exit 1
fi

install_doxygen
install_pip
install_pip_package sphinx 2.4.4
install_pip_package sphinx_rtd_theme 0.4.3
install_pip_package breathe 4.14.1
install_pip_package exhale 0.2.3
install_pip_package m2r 0.2.1

echo "*****************"
echo "Running sphinx..."
echo "*****************"
sphinx-build -M html "$DOC_SRC_DIR" "$DOC_OUT_DIR"

read -r -p "Do you want to open the generated document in your browser? [Y/n]" CONFIRM
if [[ ! $CONFIRM =~ ^[Nn]$ ]]; then
    open "$DOC_OUT_DIR/html/index.html"
fi
