name: CI

on: pull_request

jobs:
  linux-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Run debug build
      run: make TARGET=Linux all
    - name: Run release build
      run: make TARGET=Linux BUILD_TYPE=Release all
